### ISSUE TITLE
0.10.0 & scala 2.13.1 is not working...

### ISSUE THREAD

**Issue by sim732** [sirthias/scala-ssh#53]
[info] SecureCopyTest:
[info] SecureCopyTest *** ABORTED ***
[info]   java.lang.NoSuchMethodError: net.schmizz.sshj.xfer.LoggingTransferListener: method <init>()V not found
[info]   at com.decodified.scalassh.ScpTransferable.defaultListener(ScpTransferable.scala:52)
[info]   at com.decodified.scalassh.ScpTransferable.upload$default$3(ScpTransferable.scala:46)
[info]   at net.uptel.sim.scp.services.ScpService.$anonfun$uploadFile$1(ScpService.scala:34)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)
[info]   at cats.effect.IO.unsafeRunTimed(IO.scala:320)
[info]   at cats.effect.IO.unsafeRunSync(IO.scala:239)
[info]   at net.uptel.sim.scp.services.ScpService.$anonfun$uploadFiles$1(ScpService.scala:51)
[info]   at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
[info]   at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
[info]   ...

**Comment by hiiamok** [comment]
Try implicitly defining a LoggingTransferListener, e.g.:
(new LoggingTransferListener(LoggerFactory.DEFAULT))
